export type SelectorStrategy = 'test-attribute' | 'id' | 'minimal-path' | 'anchored-nth' | 'document-path';

export interface SelectorResult {
  selector: string;
  strategy: SelectorStrategy;
  unique: boolean;
}

const TEST_ATTRS = ['data-testid', 'data-test-id', 'data-cy', 'data-test'] as const;
const MAX_PATH_ANCESTORS = 4;
const MAX_ANCHOR_DEPTH = 10;
const SEMANTIC_TAGS = new Set([
  'main',
  'nav',
  'header',
  'footer',
  'aside',
  'section',
  'article',
  'form',
  'dialog',
  'table',
]);
const DESCRIPTIVE_ATTRS = ['name', 'role', 'type', 'aria-label', 'placeholder'] as const;
const NEVER_CLASSES = new Set([
  'active',
  'open',
  'show',
  'hidden',
  'selected',
  'disabled',
  'focus',
  'hover',
  'is-active',
  'is-open',
  'is-selected',
]);
export function isAutoGeneratedId(id: string): boolean {
  if (!id) return true;
  if (/^:[a-zA-Z0-9]+:$/.test(id) || id.includes(':r')) return true;
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) return true;
  if (/^\d+$/.test(id)) return true;
  if (/^[a-z]{1,4}[-_]?\d{4,}$/i.test(id)) return true;
  if (/^[0-9a-f]{16,}$/i.test(id)) return true;
  if (/^(mui|radix|headlessui|reach|downshift|rc|ember|ext-gen|yui)[-_:]/i.test(id)) return true;
  if (/[-_][0-9a-z]{8,}$/i.test(id) && /\d/.test(id) && !/[-_][a-z]+$/i.test(id)) return true;
  return false;
}
export function isSemanticId(id: string): boolean {
  return Boolean(id) && id.length <= 80 && !isAutoGeneratedId(id);
}
export function isStableClass(cls: string): boolean {
  if (!cls || cls.length > 60) return false;
  if (NEVER_CLASSES.has(cls.toLowerCase())) return false;
  if (/^(css|sc|jsx|emotion|styled)-[0-9a-z]+$/i.test(cls)) return false;
  const moduleTail = /__([0-9a-zA-Z]{5,})$/.exec(cls)?.[1];
  if (moduleTail && /\d/.test(moduleTail)) return false;
  if (/^[0-9a-f]{6,}$/i.test(cls)) return false;
  if (/^[a-z]+[-_][0-9a-f]{6,}$/i.test(cls)) return false;
  if (!/[a-z]/i.test(cls)) return false;
  return true;
}
export function cssEscape(value: string): string {
  const g = globalThis as { CSS?: { escape?: (v: string) => string } };
  if (typeof g.CSS?.escape === 'function') return g.CSS.escape(value);
  let out = '';
  for (let i = 0; i < value.length; i += 1) {
    const code = value.charCodeAt(i);
    const char = value[i] as string;
    if (code === 0) {
      out += '�';
    } else if (
      (code >= 0x01 && code <= 0x1f) ||
      code === 0x7f ||
      (i === 0 && code >= 0x30 && code <= 0x39) ||
      (i === 1 && code >= 0x30 && code <= 0x39 && value.charCodeAt(0) === 0x2d)
    ) {
      out += `\\${code.toString(16)} `;
    } else if (code >= 0x80 || char === '-' || char === '_' || /[a-zA-Z0-9]/.test(char)) {
      out += char;
    } else {
      out += `\\${char}`;
    }
  }
  return out;
}
function quoteAttr(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
function rootOf(el: Element): Document | ShadowRoot {
  const root = el.getRootNode();
  if (root instanceof ShadowRoot) return root;
  return el.ownerDocument;
}
export function resolvesTo(selector: string, el: Element): boolean {
  try {
    const root = rootOf(el);
    const matches = root.querySelectorAll(selector);
    return matches.length === 1 && matches[0] === el;
  } catch {
    return false;
  }
}
function tagOf(el: Element): string {
  return el.tagName.toLowerCase();
}
function stableClasses(el: Element, limit = 2): string[] {
  const list = Array.from(el.classList).filter(isStableClass);
  list.sort((a, b) => b.length - a.length);
  return list.slice(0, limit);
}
function testAttrOf(el: Element): { attr: string; value: string } | null {
  for (const attr of TEST_ATTRS) {
    const value = el.getAttribute(attr);
    if (value && value.trim()) return { attr, value: value.trim() };
  }
  return null;
}
function tokenVariants(el: Element): string[] {
  const tag = tagOf(el);
  const variants: string[] = [];
  const test = testAttrOf(el);
  if (test) variants.push(`[${test.attr}=${quoteAttr(test.value)}]`);
  if (el.id && isSemanticId(el.id)) variants.push(`#${cssEscape(el.id)}`);
  const classes = stableClasses(el);
  if (classes.length) {
    variants.push(`${tag}.${classes.map(cssEscape).join('.')}`);
    if (classes.length > 1) variants.push(`${tag}.${cssEscape(classes[0] as string)}`);
  }
  for (const attr of DESCRIPTIVE_ATTRS) {
    const value = el.getAttribute(attr);
    if (value && value.trim() && value.length <= 60) {
      variants.push(`${tag}[${attr}=${quoteAttr(value.trim())}]`);
    }
  }
  variants.push(tag);
  return Array.from(new Set(variants));
}
export function nthOfType(el: Element): number {
  const parent = el.parentElement;
  if (!parent) return 1;
  let index = 0;
  for (const child of Array.from(parent.children)) {
    if (child.tagName === el.tagName) {
      index += 1;
      if (child === el) return index;
    }
  }
  return index || 1;
}
function isSemanticAnchor(el: Element): boolean {
  if (testAttrOf(el)) return true;
  if (el.id && isSemanticId(el.id)) return true;
  if (SEMANTIC_TAGS.has(tagOf(el))) return true;
  const role = el.getAttribute('role');
  if (role && /^(main|navigation|banner|form|dialog|region|contentinfo)$/i.test(role)) {
    return true;
  }
  return false;
}
function anchorSelectorFor(el: Element): string | null {
  const test = testAttrOf(el);
  if (test) {
    const sel = `[${test.attr}=${quoteAttr(test.value)}]`;
    if (resolvesTo(sel, el)) return sel;
  }
  if (el.id && isSemanticId(el.id)) {
    const sel = `#${cssEscape(el.id)}`;
    if (resolvesTo(sel, el)) return sel;
  }
  const tag = tagOf(el);
  if (SEMANTIC_TAGS.has(tag) && resolvesTo(tag, el)) return tag;
  const role = el.getAttribute('role');
  if (role) {
    const sel = `[role=${quoteAttr(role)}]`;
    if (resolvesTo(sel, el)) return sel;
  }
  return null;
}
function byTestAttribute(el: Element): SelectorResult | null {
  const test = testAttrOf(el);
  if (!test) return null;
  const bare = `[${test.attr}=${quoteAttr(test.value)}]`;
  if (resolvesTo(bare, el)) {
    return { selector: bare, strategy: 'test-attribute', unique: true };
  }
  const scoped = `${tagOf(el)}${bare}`;
  if (resolvesTo(scoped, el)) {
    return { selector: scoped, strategy: 'test-attribute', unique: true };
  }
  return null;
}
function byId(el: Element): SelectorResult | null {
  if (!el.id || !isSemanticId(el.id)) return null;
  const selector = `#${cssEscape(el.id)}`;
  return resolvesTo(selector, el) ? { selector, strategy: 'id', unique: true } : null;
}
function byMinimalPath(el: Element): SelectorResult | null {
  const selfVariants = tokenVariants(el);
  for (const variant of selfVariants) {
    if (resolvesTo(variant, el)) {
      return { selector: variant, strategy: 'minimal-path', unique: true };
    }
  }
  const ancestors: Element[] = [];
  let cursor = el.parentElement;
  while (cursor && ancestors.length < MAX_PATH_ANCESTORS) {
    ancestors.push(cursor);
    cursor = cursor.parentElement;
  }
  for (const self of selfVariants) {
    let chain = self;
    for (const ancestor of ancestors) {
      const anchor = anchorSelectorFor(ancestor);
      if (anchor) {
        const descendant = `${anchor} ${self}`;
        if (resolvesTo(descendant, el)) {
          return { selector: descendant, strategy: 'minimal-path', unique: true };
        }
      }
      for (const parentVariant of tokenVariants(ancestor)) {
        const candidate = `${parentVariant} > ${chain}`;
        if (resolvesTo(candidate, el)) {
          return { selector: candidate, strategy: 'minimal-path', unique: true };
        }
      }
      chain = `${tokenVariants(ancestor)[0] ?? tagOf(ancestor)} > ${chain}`;
    }
  }
  return null;
}
function byAnchoredNth(el: Element): SelectorResult {
  const steps: string[] = [];
  let cursor: Element | null = el;
  let depth = 0;
  let anchorSelector: string | null = null;
  while (cursor && depth < MAX_ANCHOR_DEPTH) {
    const parent: Element | null = cursor.parentElement;
    if (!parent) break;
    if (isSemanticAnchor(parent)) {
      const candidate = anchorSelectorFor(parent);
      if (candidate) {
        anchorSelector = candidate;
        steps.unshift(`${tagOf(cursor)}:nth-of-type(${nthOfType(cursor)})`);
        break;
      }
    }
    steps.unshift(`${tagOf(cursor)}:nth-of-type(${nthOfType(cursor)})`);
    cursor = parent;
    depth += 1;
  }
  if (anchorSelector) {
    const selector = `${anchorSelector} > ${steps.join(' > ')}`;
    if (resolvesTo(selector, el)) {
      return { selector, strategy: 'anchored-nth', unique: true };
    }
  }
  const full: string[] = [];
  let node: Element | null = el;
  while (node && node.parentElement) {
    full.unshift(`${tagOf(node)}:nth-of-type(${nthOfType(node)})`);
    node = node.parentElement;
  }
  const rootTag = node ? tagOf(node) : 'html';
  const selector = [rootTag, ...full].join(' > ');
  return { selector, strategy: 'document-path', unique: resolvesTo(selector, el) };
}
export function buildSelector(el: Element): SelectorResult {
  if (!el || el.nodeType !== 1) {
    return { selector: '', strategy: 'document-path', unique: false };
  }
  if (tagOf(el) === 'html') return { selector: 'html', strategy: 'id', unique: true };
  if (tagOf(el) === 'body') return { selector: 'body', strategy: 'id', unique: true };
  return (
    byTestAttribute(el) ??
    byId(el) ??
    byMinimalPath(el) ??
    byAnchoredNth(el)
  );
}
export function elementKey(el: Element): string {
  const parts: string[] = [];
  let node: Element | null = el;
  let depth = 0;
  while (node && depth < 12) {
    const test = testAttrOf(node);
    if (test) {
      parts.unshift(`${test.attr}=${test.value}`);
      break;
    }
    if (node.id && isSemanticId(node.id)) {
      parts.unshift(`#${node.id}`);
      break;
    }
    parts.unshift(`${tagOf(node)}[${nthOfType(node)}]`);
    node = node.parentElement;
    depth += 1;
  }
  return parts.join('/');
}
export function targetHtml(el: Element, limit = 1500): string {
  const html = el.outerHTML ?? '';
  return html.length <= limit ? html : `${html.slice(0, limit)}…`;
}
