import { beforeEach, describe, expect, it } from 'vitest';
import {
  buildSelector,
  cssEscape,
  elementKey,
  isAutoGeneratedId,
  isSemanticId,
  isStableClass,
  nthOfType,
  resolvesTo,
  targetHtml,
} from './selector.js';

function mount(html: string): void {
  document.body.innerHTML = html;
}

function $(selector: string): Element {
  const el = document.querySelector(selector);
  if (!el) throw new Error(`fixture element not found: ${selector}`);
  return el;
}

beforeEach(() => {
  document.body.innerHTML = '';
});

describe('id heuristics', () => {
  it('rejects framework-generated ids', () => {
    for (const id of [
      ':r0:',
      ':R2ab:',
      'radix-:r1:',
      '3f2504e0-4f89-11d3-9a0c-0305e82c3301',
      '1234',
      'input-9f8e7d6c5b4a3210',
      'mui-1234',
      'headlessui-menu-button-3',
      'deadbeefdeadbeef',
    ]) {
      expect(isAutoGeneratedId(id), id).toBe(true);
      expect(isSemanticId(id), id).toBe(false);
    }
  });

  it('accepts hand-written ids', () => {
    for (const id of ['checkout-form', 'main-nav', 'hero', 'user_profile_card', 'signUpButton']) {
      expect(isAutoGeneratedId(id), id).toBe(false);
      expect(isSemanticId(id), id).toBe(true);
    }
  });
});

describe('class heuristics', () => {
  it('rejects hashed and state classes', () => {
    for (const cls of [
      'css-1x2y3z',
      'sc-fzXfPJ',
      'jsx-1234567',
      'Button_root__a1B2c',
      'a1b2c3d4e5',
      'active',
      'is-open',
    ]) {
      expect(isStableClass(cls), cls).toBe(false);
    }
  });

  it('accepts authored class names', () => {
    for (const cls of ['btn-primary', 'card', 'site-header', 'text-lg', 'checkout__summary']) {
      expect(isStableClass(cls), cls).toBe(true);
    }
  });
});

describe('buildSelector priority', () => {
  it('prefers data-testid over everything else', () => {
    mount(`
      <main id="app">
        <button id="save" class="btn btn-primary" data-testid="save-button">Save</button>
      </main>
    `);
    const result = buildSelector($('#save'));
    expect(result.strategy).toBe('test-attribute');
    expect(result.selector).toBe('[data-testid="save-button"]');
    expect(result.unique).toBe(true);
  });

  it('supports data-cy and data-test', () => {
    mount(`<div data-cy="cart">a</div><span data-test="total">b</span>`);
    expect(buildSelector($('[data-cy="cart"]')).selector).toBe('[data-cy="cart"]');
    expect(buildSelector($('[data-test="total"]')).selector).toBe('[data-test="total"]');
  });

  it('escapes quotes inside test attribute values', () => {
    mount(`<div data-testid='say "hi"'>x</div>`);
    const result = buildSelector($('div'));
    expect(result.unique).toBe(true);
    expect(document.querySelector(result.selector)).toBe($('div'));
  });

  it('falls back from a duplicated test attribute to a path', () => {
    mount(`
      <ul id="rows">
        <li data-testid="row"><span class="label">one</span></li>
        <li data-testid="row"><span class="label">two</span></li>
      </ul>
    `);
    const second = document.querySelectorAll('li')[1] as Element;
    const result = buildSelector(second);
    expect(result.unique).toBe(true);
    expect(document.querySelector(result.selector)).toBe(second);
  });

  it('uses a semantic id when there is no test attribute', () => {
    mount(`<section><form id="checkout-form"><input name="email"></form></section>`);
    const result = buildSelector($('#checkout-form'));
    expect(result.strategy).toBe('id');
    expect(result.selector).toBe('#checkout-form');
  });

  it('skips auto-generated ids and finds another unique path', () => {
    mount(`
      <main>
        <div id=":r0:" class="css-1x2y3z">
          <button class="btn-primary">Go</button>
        </div>
      </main>
    `);
    const result = buildSelector($('button'));
    expect(result.selector).not.toContain(':r0:');
    expect(result.selector).not.toContain('css-1x2y3z');
    expect(result.unique).toBe(true);
    expect(document.querySelector(result.selector)).toBe($('button'));
  });

  it('builds a minimal path within four ancestors', () => {
    mount(`
      <main id="app">
        <aside class="sidebar"><a class="link">one</a></aside>
        <section class="content"><a class="link">two</a></section>
      </main>
    `);
    const target = $('.content .link');
    const result = buildSelector(target);
    expect(result.strategy).toBe('minimal-path');
    expect(result.unique).toBe(true);
    expect(document.querySelector(result.selector)).toBe(target);
    expect(result.selector.split('>').length).toBeLessThanOrEqual(3);
  });

  it('anchors an nth-of-type path to the nearest semantic ancestor', () => {
    mount(`
      <div><div><div>
        <nav>
          <div><div>first</div><div>second</div><div>third</div></div>
        </nav>
      </div></div></div>
    `);
    const target = document.querySelectorAll('nav div div')[1] as Element;
    const result = buildSelector(target);
    expect(['anchored-nth', 'minimal-path', 'document-path']).toContain(result.strategy);
    expect(result.unique).toBe(true);
    expect(document.querySelector(result.selector)).toBe(target);
  });

  it('handles html and body', () => {
    expect(buildSelector(document.body).selector).toBe('body');
    expect(buildSelector(document.documentElement).selector).toBe('html');
  });
});

describe('quality gate: every selector resolves back to its element', () => {
  const FIXTURE = `
    <header class="site-header">
      <nav role="navigation">
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="/pricing" class="nav-link">Pricing</a></li>
          <li><a href="/docs" class="nav-link">Docs</a></li>
        </ul>
      </nav>
    </header>
    <main id="app">
      <section class="hero">
        <h1 class="css-1a2b3c">Ship faster</h1>
        <p id=":r7:">Subtitle</p>
        <button data-testid="cta" class="btn btn-primary">Start</button>
      </section>
      <section class="grid">
        <article class="card"><h2>One</h2><button class="btn">Buy</button></article>
        <article class="card"><h2>Two</h2><button class="btn">Buy</button></article>
        <article class="card"><h2>Three</h2><button class="btn">Buy</button></article>
      </section>
      <form id="checkout-form">
        <input name="email" type="email" placeholder="Email">
        <input name="card" type="text">
        <select name="plan"><option>a</option><option>b</option></select>
        <button type="submit" data-cy="submit">Pay</button>
      </form>
      <table><tbody>
        <tr><td>r1c1</td><td>r1c2</td></tr>
        <tr><td>r2c1</td><td>r2c2</td></tr>
      </tbody></table>
    </main>
    <footer><span>© 2026</span></footer>
  `;

  it('resolves for every element in a realistic page', () => {
    mount(FIXTURE);
    const all = Array.from(document.querySelectorAll('*'));
    expect(all.length).toBeGreaterThan(30);

    const failures: string[] = [];
    for (const el of all) {
      const { selector } = buildSelector(el);
      let resolved: Element | null = null;
      try {
        resolved = document.querySelector(selector);
      } catch {
        failures.push(`${el.tagName}: invalid selector ${selector}`);
        continue;
      }
      if (resolved !== el) {
        failures.push(`${el.tagName}: ${selector} -> ${resolved?.tagName ?? 'null'}`);
      }
    }
    expect(failures).toEqual([]);
  });

  it('reports uniqueness honestly', () => {
    mount(FIXTURE);
    for (const el of Array.from(document.querySelectorAll('*'))) {
      const result = buildSelector(el);
      expect(result.unique, result.selector).toBe(resolvesTo(result.selector, el));
    }
  });
});

describe('helpers', () => {
  it('computes nth-of-type among same-tag siblings only', () => {
    mount(`<div><span>a</span><p>b</p><span>c</span><span>d</span></div>`);
    const spans = document.querySelectorAll('span');
    expect(nthOfType(spans[0] as Element)).toBe(1);
    expect(nthOfType(spans[1] as Element)).toBe(2);
    expect(nthOfType(spans[2] as Element)).toBe(3);
    expect(nthOfType(document.querySelector('p') as Element)).toBe(1);
  });

  it('produces a stable element key that ignores unstable ids', () => {
    mount(`<main><div id=":r1:"><span>x</span><span>y</span></div></main>`);
    const target = document.querySelectorAll('span')[1] as Element;
    const key = elementKey(target);
    expect(key).not.toContain(':r1:');
    expect(elementKey(target)).toBe(key);
    expect(key.endsWith('span[2]')).toBe(true);
  });

  it('anchors the element key on a test attribute when present', () => {
    mount(`<div data-testid="panel"><b>x</b></div>`);
    expect(elementKey($('b'))).toBe('data-testid=panel/b[1]');
  });

  it('truncates html to the daemon limit', () => {
    mount(`<div>${'x'.repeat(4000)}</div>`);
    const html = targetHtml($('div'), 1500);
    expect(html.length).toBe(1501);
    expect(html.endsWith('…')).toBe(true);
  });

  it('escapes selector-hostile characters', () => {
    expect(cssEscape('a.b')).toContain('\\');
  });
});
